---
title: "Teaching Philosophy"
editor: visual
---

## 11/30/2023

My philosophy of education is facilitating a classroom experience that ensures the success of all
students. Everyone comes from diverse backgrounds comprising both personal and professional
experiences. These experiences allow students to bring boundless prior insight and knowledge to their
undergraduate and graduate education, including cognitive modes. It is my desire to promote a classroom
that ensures no matter the learning style, students can not only succeed, but fail and learn with one
another. Through real-world problems and examples, students will be challenged to use new and prior
knowledge to critically think and evaluate different subject matter. 

Through hands-on opportunities and peer led learning activities, students will be able to work through
active critical thinking as well as gain experience in disseminating information, which ultimately will
allow them to understand the subject matter more effectively. I will also task students with
reflections to ensure that each student is supported and has their educational needs met in my
classroom. Without feedback, I cannot confirm that my methods are working for each student; and if I am
not supporting each individual student appropriately, then I am failing as an instructor. 

I aim to bring an open mind, good energy, and high expectations to each class. I will challenge
students to escape their comfort zone and leave their pride at the door. I believe that you teach how
you think best until you know better. By this, I mean I will adapt to my students’ needs and may very
well change my philosophy over time. This is ok because learning is a lifelong process, and I will be
learning from my students as they learn from me. 

